### ISSUE TITLE
言語処理における分散表現学習のフロンティア のリンク切れ

### ISSUE THREAD

**Issue by Issei0804-ie** [naltoma/datamining_intro2021#1]
https://github.com/naltoma/datamining_intro2021/blob/b873a84d39518391c5cf37df339d26f0398b185e/4-nlp/nlp1.md?plain=1#L196

上記箇所のリンクが切れてました!!

**Comment by naltoma** [comment]
當間です。

連絡ありがとうございます！

アーカイバ役割持ってた気もするので、一時的な問題かもしれないですが、
しばらく様子見で直らなさそうなら修正します。

> 2022/06/22 13:27、Issei ***@***.***>のメール:
> 
> 
> https://github.com/naltoma/datamining_intro2021/blob/b873a84d39518391c5cf37df339d26f0398b185e/4-nlp/nlp1.md?plain=1#L196
> 
> 上記箇所のリンクが切れてました!!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

----
 Naruaki Toma
 E-mail: ***@***.***, Tel: 098-895-8830
 http://ie.u-ryukyu.ac.jp/~tnal/

**Comment by naltoma** [comment]
復活しなさそうなのでJ-STAGE側に修正しました。
